In [4]:
import numpy as np
y = np.asarray([1, 0, 0, 1, 1, 1, 1, 0, 0])

In [6]:
y[y==1]

array([1, 1, 1, 1, 1])

In [7]:
X = np.array([[1,2,3],[4,5,6]])


In [8]:
X[0]

array([1, 2, 3])

In [9]:
X[0]+X[1]

array([5, 7, 9])

In [14]:
d = {0:[1,2,3,4],1:[2,3,4,5]}

In [32]:
d['justin'] = np.array([5,6,7,8])
d[1]+d['justin']

array([ 7,  9, 11, 13])

In [16]:
d.iteritems()

<dictionary-itemiterator at 0x104f6f418>

In [17]:
for l, v in d.iteritems():
    print l, v

0 [1, 2, 3, 4]
1 [2, 3, 4, 5]


In [19]:
np.argmax

<function numpy.core.fromnumeric.argmax>

In [27]:
values = [(2, 4.5), (1, 5.5)]
sorted(values, key=lambda x:x[1], reverse=True)[0][0]


1

In [ ]:
for i, label in enumerate(y):
    for j, count in enumerate(X[i]):
        prob[i,j] += count # per_feature_per_label