##RAT 2.1

This is a classic dynamic programming question. 

Find the subarray of a given array of integers whose sum is maximum.

For example, in the array [1, -2, 3, 10, -4, 7, 2, -5], its sub-array [3, 10, -4, 7, 2] has the maximum sum 18.


In [1]:
import numpy as np

test = np.array([1,-2,3,10,-4,7,2,-5])



In [223]:
def sub_array(input_array):
    M = np.zeros([len(input_array),len(input_array)])

    
    for sorted_array_count,number in enumerate(input_array): # go through each number in the list
        for number_count,size_of_subarray in enumerate(range(len(input_array))):
            if sorted_array_count==0: ## initial case, put the first number in M, this is your largest number
                M[sorted_array_count,number_count]=max(input_array)
            else:
                #Four way comparison either the number above, the number from the start of the string to the current
                #The number starting at the end of the string, OR the numbers in the middle.
                

                M[sorted_array_count,number_count]=max(sum(input_array[:sorted_array_count]),\
                                                       M[sorted_array_count-1,number_count],\
                                                      sum(input_array[-sorted_array_count:]),\
                                                      sum(input_array[number_count:sorted_array_count]))
                

    max_row = 0
    row_num = 0
    
    for row_number,row in enumerate(M):
        
        if max(row) > max_row:
            max_row=max(row)
            row_num=row_number
            

            
    #print(row_num,'row num') 
    #print(M)
    index_of_max = list(M[row_num]).index(max_row)
    #print(index_of_max)
    #print(max_row, ' the max sum of your sub array is this')
    #print(input_array[index_of_max:row_num], ' This is the sub array')
    return(max_row,input_array[index_of_max:row_num],)
            
            
    

In [224]:
sub_array(test)

(18.0, array([ 3, 10, -4,  7,  2]))

In [171]:
sub_array(l)

[[ 4.  4.  4.]
 [ 4.  4.  4.]
 [ 5.  5.  5.]]
5.0  the max sum of your sub array is this
[1, 4]  This is the sub array


In [167]:
testing = [2,3,-3,-4,-2,4,10,5,1,2,-3,8,-7]

In [168]:
sub_array(testing)

27.0  the max sum of your sub array is this
[4, 10, 5, 1, 2, -3, 8]  This is the sub array


In [221]:
def sub_array2(input_list):
    M=np.zeros(len(input_list))
    M[0]=input_list[0]
    
    for i in range(len(input_list)):

        M[i]=max(input_list[i]+M[i-1],input_list[i])
    

    return max(M)
            

In [222]:
%timeit sub_array2(test)

10000 loops, best of 3: 30.9 µs per loop


In [225]:
%timeit sub_array(test)

1000 loops, best of 3: 408 µs per loop
