# DSCI 6003 1.4 Lab

Today you are to solve a dynamic programming problem from scratch: [Interviewcake #16](https://www.interviewcake.com/question/java/cake-thief)

Repeated below:

You are a renowned thief who has recently switched from stealing precious metals to stealing cakes because of the insane profit margins. You end up hitting the jackpot, breaking into the world's largest privately owned stock of cakes—the vault of the Queen of England.
While Queen Elizabeth has a limited number of types of cake, she has an unlimited supply of each type.

Each type of cake has a weight and a value, stored in objects of a CakeType class:

    class CakeType:
        def __init__(self, typename, weight, value):
            self.typename = typename
            self.weight = weight
            self.value = value

i.e. cake1 = CakeType(chocolate, 3, 50)

Begin by diagramming the solution and drawing a paralell to other problems we have discussed in class. Work through the solution step by step without drilling through the internet. You might consider a simpler problem first.

Good luck. 

In [354]:
class CakeType:
    def __init__(self, typename, weight, value):
        self.typename = typename
        self.weight = weight
        self.value = value
        
#cake_tuples = [(7, 160), (3, 90), (2, 15)]
# capacity    = 20

# max_duffel_bag_value(cake_tuples, capacity)

In [355]:
cake1 = CakeType('chocolate',7,160)
cake1.value

160

In [422]:
cake2 = CakeType('vanilla',3,90)

In [ ]:
 # cake_tuples = [(7, 160), (3, 90), (2, 15)]

In [423]:

cake5 = CakeType('small_cake',2,15)
all_cakes = [cake1,cake2,cake5]

In [358]:
## Unlimited number of cakes , want to maximize the value 
##  create table and index
## Sttempt number one doesn't work that well

def cake_stealing(list_of_cakes,weight_of_bag):
    """Return the max value of different cakes"""
    
    max_values_at_each_weight = {}
    length = len(list_of_cakes)
    
    M = np.zeros((length,weight_of_bag+1))
    
    #sort the cakes by the weight
    
    cakes_list = [(list_of_cakes[item].typename,list_of_cakes[item].weight,list_of_cakes[item].value) \
                  for item in range(len(list_of_cakes))]
    cakes_list_sorted = sorted(cakes_list, key = lambda tup: tup[1])
    #name , weight , value
    for weight in range(weight_of_bag+1):
        first_weight = 0
        first_value = 0
        first_count = 0
        while first_count <= weight:
            
            first_weight +=cakes_list_sorted[0][1]
            first_value +=  cakes_list_sorted[0][2]
            first_count +=1
        if weight+1>=np.shape(M)[1]: ## so that we do not go over the number of columns
            pass
        else:
            M[0,weight+1] = first_value ##multiples of the smallest one
        for cake_count,cake in enumerate(cakes_list_sorted): #go through each cake
            
            if weight ==0 and cake_count ==0:
                M[:,0]=0
            elif weight_of_bag ==0:
                return 0
            else:
                if cake[1]>weight:    #weight greater than current bag weight
                    M[cake_count,weight] = M[cake_count-1,weight] ##take previous value
                
                
                elif cake[1]<=weight and cake_count!=0: #cake weight less than current bag weight
                    
                    current_weight=cake[1]
                    current_value =cake[2]
                    count=1
                    
                    while current_weight<=weight: #use this to find the number of multiple cakes you want to take
                        current_weight += cake[1]
                        if current_weight > weight:
                            break
                        current_value +=cake[2]
                        count+=1
                    
                    #Compare three values, the one above you in the matrix, the difference in weight, and multiple
                    #of the current cake
                    M[cake_count,weight] = max (M[cake_count-1,weight],\
                                                M[cake_count-1, weight-cake[1]]+cake[2],\
                                               current_value )
                
         
            
    print(M)  
    return max(M[:,weight_of_bag])
    
    

In [359]:
cake_stealing(all_cakes,6)

[[   0.    0.   30.   45.   60.   75.   90.]
 [   0.    0.   30.   90.   90.  120.  180.]
 [   0.    0.   30.   90.   90.  120.  180.]]


180.0

In [360]:
print(np.shape(test))

(2, 3)


In [499]:
#attempt number two

def cake_stealer(list_of_cakes,bag_weight):
    """Unbounded knapsack problem"""
    ## recode
# four cases,  1) one above  2) current one multipled by even divisible 
#3) current one divisibiel by num, leftover take from the index
#4) value of that item if it goes in evenly
    length = len(list_of_cakes)
    M = np.zeros((length,bag_weight+1))
    
    #sort the cakes by the weight
    
    cakes_list = [(list_of_cakes[item].typename,list_of_cakes[item].weight,list_of_cakes[item].value) \
                  for item in range(len(list_of_cakes))]
    cakes_list_sorted = sorted(cakes_list, key = lambda tup: tup[1])
    #name , weight , value
    print(cakes_list_sorted)
    
    max_row = 0
    max_column =0
    max_row_two = 0
    max_column_two = 0
   
    for weight in range(bag_weight+1):
         for cake_count,cake in enumerate(cakes_list_sorted):
      
            if weight ==0:
                M[cake_count,weight]=0
            elif cake[1]>weight:
                M[cake_count,weight]= M[cake_count-1,weight]
            else:
                
            
                M[cake_count,weight] = max(M[cake_count-1,weight], int(weight/cake[1])*cake[2] , \
                                           int(weight/cake[1]) *cake[2] + M[ cake_count-1,(weight%cake[1]) ]   )
    
                
                if M[cake_count-1,weight] > int(weight/cake[1])*cake[2] and \
                    M[cake_count-1,weight] > int(weight/cake[1]) *cake[2] + M[ cake_count-1,(weight%cake[1])]  :
                    max_row = cake_count-1
                    max_column = weight
                elif int(weight/cake[1])*cake[2] >M[cake_count-1,weight] and \
                    int(weight/cake[1])*cake[2] > int(weight/cake[1]) *cake[2] + M[ cake_count-1,(weight%cake[1]) ]:
                        max_row = cake_count
                        max_column = weight
                elif int(weight/cake[1]) *cake[2] + M[ cake_count-1,(weight%cake[1]) ] > M[cake_count-1,weight] and\
                    int(weight/cake[1]) *cake[2] + M[ cake_count-1,(weight%cake[1]) ] > int(weight/cake[1])*cake[2]:
                        max_row = cake_count
                        max_column = weight
                        max_row_two = cake_count-1
                        max_column_two = weight%cake[1]
                        
        
    
    print(M)
    max_num = max(M[:,(bag_weight)])
    print(max(M[:,(bag_weight)]))
    
#     print(max_row,'max row')
#     print(max_column,'max column')
#     print(max_row_two,'max row two')
#     print(max_column_two,'max col two')
    
    if max_row_two ==0 and max_column_two ==0:
        #cakes_list_sorted[max_row]
        
        print(M[max_row,max_column]/cakes_list_sorted[max_row][2] , "number of cakes")
    else:
        
        print(int(M[max_row,max_column]/cakes_list_sorted[max_row][2]), cakes_list_sorted[max_row], "cakes taken")  
        print(M[max_row_two,max_column_two]/cakes_list_sorted[max_row_two][2], cakes_list_sorted[max_row_two],"cakes taken")
    

In [502]:
cake_stealer(all_cakes,20)

[('small_cake', 2, 15), ('vanilla', 3, 90), ('chocolate', 7, 160)]
[[   0.    0.   15.   15.   30.   30.   45.   45.   60.   60.   75.   75.
    90.   90.  105.  105.  120.  120.  135.  135.  150.]
 [   0.    0.   15.   90.   90.  105.  180.  180.  195.  270.  270.  285.
   360.  360.  375.  450.  450.  465.  540.  540.  555.]
 [   0.    0.   15.   90.   90.  105.  180.  180.  195.  270.  270.  285.
   360.  360.  375.  450.  450.  465.  540.  540.  555.]]
555.0
6 ('vanilla', 3, 90) cakes taken
1.0 ('small_cake', 2, 15) cakes taken
